In [1]:
from pathlib import Path
import pandas as pd

In [2]:
item_list_2016_csv = Path("./mndot_bid_etl/data/csv/item_list_2016.csv").resolve()
item_list_2018_csv = Path("./mndot_bid_etl/data/csv/item_list_2018.csv").resolve()
item_list_2020_csv = Path("./mndot_bid_etl/data/csv/item_list_2020.csv").resolve()

In [5]:
read_csv_2016_kwargs = {
    "dtype": "str",
    "quotechar": "'",
    "header": "infer",
    # "skiprows": 3713,
    # "nrows": 11,
}

item_list_2016 = pd.read_csv(item_list_2016_csv, **read_csv_2016_kwargs)
item_list_2016.head(11)

       Item Number        Short Description  ... Spec Year Unnamed: 6
0   2011.601/00003   CONSTRUCTION SURVEYING  ...        16        NaN
1   2011.601/00010     VIBRATION MONITORING  ...        16        NaN
2   2011.601/00015         SCOUR MONITORING  ...        16        NaN
3   2011.601/00020     REVISED BRIDGE PLANS  ...        16        NaN
4   2011.601/00040                   DESIGN  ...        16        NaN
5   2011.601/00050       DESIGN & CONSTRUCT  ...        16        NaN
6   2011.601/01000                 AS BUILT  ...        16        NaN
7   2012.602/00010  TRAFFIC CONTROL SPECIAL  ...        16        NaN
8   2012.602/00011   TRAFFIC CONTROL TYPE 1  ...        16        NaN
9   2012.602/00012   TRAFFIC CONTROL TYPE 2  ...        16        NaN
10  2012.602/00013   TRAFFIC CONTROL TYPE 3  ...        16        NaN

[11 rows x 7 columns]

In [6]:
pipe_aprons_2016 = item_list_2016.iloc[3712:3722]
pipe_aprons_2016.head(20)

         Item Number Short Description  ... Spec Year Unnamed: 6
3714  2501.602/00418    18" PIPE APRON  ...        16        NaN
3715  2501.602/00421    21" PIPE APRON  ...        16        NaN
3716  2501.602/00424    24" PIPE APRON  ...        16        NaN
3717  2501.602/00427    27" PIPE APRON  ...        16        NaN
3718  2501.602/00430    30" PIPE APRON  ...        16        NaN
3719  2501.602/00436    36" PIPE APRON  ...        16        NaN
3720  2501.602/00442    42" PIPE APRON  ...        16        NaN
3721  2501.602/00448    48" PIPE APRON  ...        16        NaN
3722  2501.602/00472    72" PIPE APRON  ...        16        NaN
3723  2501.602/00512  12" SAFETY APRON  ...        16        NaN

[10 rows x 7 columns]